#!/bin/sh
# [Gedit Tool]
# Save-files=all
# Output=nothing
# Applicability=all
# Name=Session Save
# Input=document
# Shortcut=<Primary><Alt>s

mkdir -p ~/Projects/Gedit-Sessions/
FILE=

FILE=`zenity --file-selection --save --title='Save Session As...' --filename="$HOME/Projects/Gedit-Sessions/"`
if [ ! -z "$FILE" ]; then
	echo $GEDIT_DOCUMENTS_PATH > $FILE
	echo "Saved session to "$FILE""
fi
