#!/bin/sh
# [Gedit Tool]
# Name=Session Restore
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Shortcut=<Primary><Alt>r

sessions_path="$HOME/.config/Gedit-Sessions"
current_session_path_path="$sessions_path/.current_session_path"
if [ -d "$sessions_path" ]; then
  FILE=`zenity --file-selection --title="Restore Session" --filename="$sessions_path"`
  if [ ! -z "$FILE" ]; then
    if [ "$FILE" == "$current_session_path_path" ]; then
      # zenity --error --text="ERROR in Session Restore: '$FILE' is the configuration file for Session Restore, not a session. Try choosing another file."
      # is the session file (that contains the name of the file that contains the names of the files) so unwind one step first:
      FILE=`cat "$FILE"`
    fi
    cat "$FILE"  | xargs gedit --new-window
    echo "Restored Session from '$FILE'"
    echo "$FILE" > "$current_session_path_path"
  else
    file_msg="empty or inaccessible"
    if [ ! -f "$FILE" ]; then
      file_msg="missing"
    fi
    zenity --error --text="ERROR in Session Restore: Session file '$FILE' is $file_msg."
  fi
else
  zenity --error --text="ERROR in Session Restore: You did not save any sessions yet (no '$sessions_path'). Try opening some files then do Ctrl Alt S"
fi
