#!/bin/sh
# [Gedit Tool]
# Name=Session Save
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Shortcut=<Primary><Alt>s

sessions_path="$HOME/.config/Gedit-Sessions"
current_name_path="$sessions_path/.current_name"
if [ ! -d "$sessions_path" ]; then
  mkdir -p "$sessions_path"
fi
if [ -f "$current_name_path" ]; then
  FILE=`cat "$current_name_path"`
    echo $GEDIT_DOCUMENTS_PATH > $FILE
  if [ -f "$FILE" ]; then
    echo "Saved session to "$FILE""
  else
    zenity --error --text="ERROR in Session Save: could not save current session '$FILE'. Try editing '$current_name_path' and make sure it contains only a full and writable file path (normally in the same folder)."
  fi
else
  if [ -f "session-save-as" ]; then
    sh "session-save-as"
  else
    zenity --error --text="Do 'Ctrl Alt A' to 'Save Session As' first."
  fi
fi
