#!/bin/sh
# [Gedit Tool]
# Name=Session Save As
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Shortcut=<Primary><Alt>a

sessions_path="$HOME/.config/Gedit-Sessions"
current_session_path_path="$sessions_path/.current_session_path"
if [ ! -d "$sessions_path" ]; then
  mkdir -p "$sessions_path"
fi
# FILE=
# if [ -f "$(command -v qarma)"]; then
# FILE=`zenity --file-selection --save --title='Save Session As...' --filename="$HOME/Gedit-Sessions/"`
# if [ ! -z "$FILE" ]; then
# qarma-git (qarma is a drop-in replacement for zenity) does not honor --save for some reason (only allows choosing an existing file, and has open button), so:
FILE="$sessions_path/$(uuidgen)"
echo $GEDIT_DOCUMENTS_PATH > $FILE
if [ -f "$FILE" ]; then
  msg="Saved as '$FILE'. Rename file manually using your favorite file manager or terminal if desired (you must also change the name in '$current_session_path_path' if you rename the session currently loaded)."
  echo "$msg"
  echo "$FILE" > "$current_session_path_path"
  if [ -f "$current_session_path_path" ]; then
    current_session_path=`cat "$current_session_path_path"`
    if [ ! -f "$current_session_path" ]; then
      msg="ERROR in Session Save As: Could not write path (got unreadable path '$current_session_path') correctly to file '$current_session_path_path'--make sure that file is writeable."
    fi
  else
    msg="ERROR in Session Save As: Could not write current session path to '$current_session_path_path'. Make sure the path is writeable."
    echo "$msg"
    zenity --error --text="$msg"
  fi
else
  zenity --error --text="ERROR in Session Save As: Could not write '$FILE'. Make sure the path is writeable."
fi
