#!/bin/sh
# [Gedit Tool]
# Name=Session Save
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Shortcut=<Primary><Alt>s

sessions_path="$HOME/.config/Gedit-Sessions"
current_session_path_path="$sessions_path/.current_session_path"
if [ ! -d "$sessions_path" ]; then
  mkdir -p "$sessions_path"
fi
if [ -f "$current_session_path_path" ]; then
  FILE=`cat "$current_session_path_path"`
  QUOTED_PATHS="\""
  #IFS=$' '  # Internal Field Separator
  build_spacey_path=""
  for this_path in $GEDIT_DOCUMENTS_PATH
  do
    if [ ! -z "$this_path" ]; then
      delimiter="\" \""
      if [ "$QUOTED_PATHS" = "\"" ]; then
        delimiter=""
      fi
      if [ -f "$this_path" ]; then
        QUOTED_PATHS="$QUOTED_PATHS$delimiter$this_path"
      else
        if [ ! -z "$build_spacey_path" ]; then
          build_spacey_path="$build_spacey_path$this_path"
          if [ -f "$build_spacey_path" ]; then
            QUOTED_PATHS="$QUOTED_PATHS$delimiter$build_spacey_path"
            build_spacey_path=""
          fi
        else
          build_spacey_path="$this_path "
        fi
      fi
    fi
  done
  QUOTED_PATHS="$QUOTED_PATHS\""
  echo $QUOTED_PATHS > $FILE
  if [ -f "$FILE" ]; then
    echo "Saved session to "$FILE""
  else
    zenity --error --text="ERROR in Session Save: could not save current session '$FILE'. Try editing '$current_session_path_path' and make sure it contains only a full and writable file path (normally in the same folder)."
  fi
else
  if [ -f "session-save-as" ]; then
    sh "session-save-as"
  else
    zenity --error --text="Do 'Ctrl Alt A' to 'Save Session As' first."
  fi
fi
